/*
<MODULE_CONTRACT>
<purpose>
  RFC-0052 robots.txt generation. Pure function buildRobotsTxt produces the
  robots exclusion standard file from a structured RobotsPolicy config.
</purpose>
<non-goals>
  <item>Do not read content files or validate input — the caller is responsible.</item>
  <item>Do not manage default policy fallback — caller decides skip vs fallback.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0052: Initial implementation.</item>
  <item>RFC-0784: Add contentSignal field and Content-Signal directive output.</item>
</CHANGE_SUMMARY>
*/

export interface RobotsRule {
  userAgent: string;
  disallow: string[];
  allow: string[];
}

export interface RobotsPolicy {
  defaultPolicy?: "allow" | "disallow";
  disallowedPaths?: string[];
  allowedPaths?: string[];
  crawlerBlocklist?: string[];
  crawlerAllowlist?: string[];
  sitemap?: string;
  customRules?: RobotsRule[];
  /** RFC-0784: Content-Signal directive — AI usage preferences (ai-train, search, ai-input). */
  contentSignal?: string[];
}

export function buildRobotsTxt(policy: RobotsPolicy): string {
  const lines: string[] = [];

  lines.push("# robots.txt");
  lines.push(`# Generated by robots.generate (RFC-0052)`);
  lines.push("");

  // RFC-0784: Content-Signal directive — placed after header comment, before User-agent block.
  if (policy.contentSignal && policy.contentSignal.length > 0) {
    lines.push(`Content-Signal: ${policy.contentSignal.join(", ")}`);
    lines.push("");
  }

  const defaultPolicy = policy.defaultPolicy ?? "allow";
  const defaultDisallow = policy.disallowedPaths ?? [];
  const defaultAllow = policy.allowedPaths ?? [];
  const blocklist = policy.crawlerBlocklist ?? [];
  const allowlist = policy.crawlerAllowlist ?? [];
  const customRules = policy.customRules ?? [];

  // Default User-agent group
  lines.push("# Default crawl policy");
  lines.push("User-agent: *");

  if (defaultPolicy === "disallow") {
    if (defaultDisallow.length === 0) {
      lines.push("Disallow: /");
    } else {
      for (const path of defaultDisallow) {
        lines.push(`Disallow: ${path}`);
      }
    }
  } else if (defaultDisallow.length > 0 || defaultAllow.length > 0) {
    // Default allow with specific overrides
    for (const path of defaultAllow) {
      lines.push(`Allow: ${path}`);
    }
    for (const path of defaultDisallow) {
      lines.push(`Disallow: ${path}`);
    }
  }
  // Default allow with no overrides — omit redundant "Allow: /" (PUBTXT-09);
  // the auxiliary discovery files below are explicitly allowed.

  // Auxiliary discovery files — explicitly allowed for all crawlers
  lines.push("");
  lines.push("# Auxiliary discovery files — explicitly allowed for all crawlers");
  lines.push("Allow: /robots.txt");
  lines.push("Allow: /llms.txt");
  lines.push("Allow: /llms-full.txt");
  lines.push("Allow: /sitemap.xml");
  lines.push("Allow: /sitemap-content.xml");

  // Crawler allowlist (friendly AI / search crawlers)
  if (allowlist.length > 0) {
    lines.push("");
    lines.push("# Allow known friendly crawlers explicitly");
    for (const agent of allowlist) {
      lines.push(`User-agent: ${agent}`);
    }
    lines.push("Allow: /");
  }

  // Crawler blocklist
  if (blocklist.length > 0) {
    lines.push("");
    lines.push("# Block known low-value crawlers");
    for (const agent of blocklist) {
      lines.push(`User-agent: ${agent}`);
    }
    lines.push("Disallow: /");
  }

  // Custom per-user-agent rules
  for (const rule of customRules) {
    lines.push("");
    lines.push(`User-agent: ${rule.userAgent}`);
    for (const path of rule.disallow) {
      lines.push(`Disallow: ${path}`);
    }
    for (const path of rule.allow) {
      lines.push(`Allow: ${path}`);
    }
  }

  // Sitemap reference
  const sitemap = policy.sitemap ?? "/sitemap.xml";
  lines.push("");
  lines.push(`Sitemap: ${sitemap}`);

  return lines.join("\n") + "\n";
}
